baseURL = 'https://blog.alileza.me/'
languageCode = 'en-us'
title = 'behind the keyboard'
theme = 'paper'
[params]
    subtitle = 'failure, inefficiency, and miscommunication in software engineering'
